name: Java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: |
          cd testGitHub
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd testGitHub
          ./gradlew build

      - name: Run tests
        run: |
          cd testGitHub
          ./gradlew test
