name: Run Script from Desktop

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for script
        run: |
          chmod +x ~/Desktop/Runner/script.sh
          chmod +x ~/Desktop/Runner/runJava.sh

      - name: Run script from Desktop
        run: |
          ~/Desktop/Runner/script.sh
          ~/Desktop/Runner/runJava.sh
